### PR TITLE
add loader during cluster creation

### PR DESCRIPTION
**Pull request by skant7**

### CODE REVIEW

**Comment by idoqo** [comment]
Looks okay to me (though I don't know much frontend) - also could you help add some screenshots? makes it easier to get the context too.

**Comment by skant7** [comment]
Here are some of the screenshots of the loader
Screenshot from 2022-03-24 12-01-42

Screenshot from 2022-03-24 12-01-15 (1)

**Comment by akshat2602** [comment]
The loader looks good enough but I think it should be centrally aligned instead of being slightly towards the left. Thoughts? @araa3185

**Comment by skant7** [comment]
fixed the alignment issue
Screenshot from 2022-03-26 20-18-56

**Review by akshat2602 — APPROVED** [review]

**Pull request merged**
