### PR TITLE
alternate user auth integration

### PR DESCRIPTION
**Pull request by skant7**
feat: Alternate user authentication

update docs

### CODE REVIEW

**Review by hitenSharm — COMMENTED** [review]
I have a few questions:
- What's the API key that we are asking  in the frontend <span>(Have we made some login method of our own in the backend which uses that key?)
- Are we trying to mimic GitHub's Oauth method?
If yes, then i would recommend to not do that and try to do something simpler like Google Oauth

**Comment by idoqo** [comment]
@hitenSharm Not mimic per se, the idea is that for someone to quickly try out spinup (or for development purposes), setting up a GitHub app to get a client ID and secret is quite a long process.

We need to provide a quick way for them to set up authentication - that is what the API key does. It's sort of like a default username and password I guess.

Viggy and Surya can chirp in if I'm wrong about something.

**Comment by skant7** [comment]
Yeah it just compares the API key entered with that in config.yaml and bypasses the GitHub auth by creating a dummy "testuser" just to quickly try spinup

**Comment by hitenSharm** [comment]
Oh ok now I understand. 👍

**Comment by viggy28** [comment]
You guys are exactly right. Thanks, @hitenSharm for the review.

**Pull request merged**
